POST http://localhost:3033/auth
Content-Type: application/json

{
    "action": "login",
    "name": "Baran",
    "password": "shforever"
}

###

POST http://localhost:3033/auth
Content-Type: application/json

{ "action": "login"}
