POST http://localhost:3001/auth/login
Content-Type: application/json

{
    "name": "john",
    "password": "foobar"
}

POST http://localhost:3001/auth/register
Content-Type: application/json

{
    "name": "john",
    "password": "foobar"
}
